name: 'My First GitHub Actions'

on: push

jobs:
  first-job:
    name: 'First Job'

    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Say Hello World from ${{ matrix.os }} 1
      shell: bash
      run: |
        echo "Hello World on ${{ matrix.os }} 1"

    - name: Say Hello World from ${{ matrix.os }} 2
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        echo "Hello World on ${{ matrix.os }} 2"