# 필수 : name, on, jobs
name: 'My First GitHub Actions' # 워크플로우 이름

on: # [ 'push', 'pull_request' ] # 수행할 이벤트
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:
    branches:
    - main

jobs: # 어떤 일을 할지를 정의
  call_build: # 이거 하나하나가 하나의 빌드 서버라고 보면 됨
    uses: './.github/workflows/ci.yaml'
    with:
      artifact_name: apiapp
  
  call_release_dev:
    uses: './.github/workflows/cd.yaml'
    needs: call_build
    with:
      title: latest
      artifact_name: apiapp
      env: DEV
    secrets: inherit
  
  call_release_prod:
    uses: './.github/workflows/cd.yaml'
    needs: call_release_dev
    with:
      title: latest
      artifact_name: apiapp
      env: PROD
    secrets: inherit
